### ISSUE TITLE
Bug at demo page

### ISSUE THREAD

**Issue by heejongahn** [IonicaBizau/medium-editor-markdown#19]
I'm not sure if this is bug of either demo site or the library, as I only tried the demo site. Anyway, I found this bug at this repository's demo site, so I'm reporting it here.  FYI, I tried this at Chrome and Safari, and this bug offered, but it did not occur at Firefox.

At the demo site, when I type a newline(enter) right after "**Let's test up the elements.**" part, a <div> element suddenly appears at the output markdown like this.

<img width="675" alt="ss 2016-02-18 at 4 17 00 pm" src="https://cloud.githubusercontent.com/assets/6768840/13136274/70aa6e94-d65b-11e5-9276-c858cf318696.png">

... and the entire output is like this. (You can easily reproduce this)

``` markdown
## Medium Editor

You know, the **Medium Editor** library is awesome. Just great. But there is a missing feature that some people would like to have.

It's called _Markdown_. [@IonicaBizau](https://github.com/IonicaBizau) created a Medium Editor extension that adds this missing feature.

> Walking on water and developing software from a specification are easy if both are frozen. _Edward Berard_

Let's test up the elements.

<div>

> ## First Computer Bug
>
> In 1947, Grace Murray Hopper was working on the Harvard University Mark II Aiken Relay Calculator (a primitive computer).
>
> On the 9th of September, 1947, when the machine was experiencing problems, an investigation showed that there was a moth trapped between the points of Relay #70, in Panel F.
>
> The operators removed the moth and affixed it to the log. The entry reads: "First actual case of bug being found."
>
> _[Read the whole story »](http://www.jamesshuggins.com/h/tek1/first_computer_bug.htm)_

# Heading 1

## Heading 2

### Heading 3

#### Heading 4

##### Heading 5

###### Heading 6

*   I am
*   a list
*   with 3 items

1.  I am
2.  a numbered list
3.  with 3 items

</div>
```

You can see that there is opening and closing div tag appended, which is, i guess, unintended.

Thanks!

**Comment by IonicaBizau** [comment]
Indeed an issue... :+1: This would be probably resolved when fixing #6. Check out this comment: https://github.com/IonicaBizau/medium-editor-markdown/issues/6#issuecomment-154776502

If somebody has time to fix this it would be great. I'm currently busy with other projects, but I'm happy to accept contributions. :sparkle:
