### ISSUE TITLE
Uncaught ReferenceError: merge is not defined

### ISSUE THREAD

**Issue by antonagestam** [IonicaBizau/medium-editor-markdown#2]
Using the standalone version i get "Uncaught ReferenceError: merge is not defined" when running the script. It looks like it's the code from he.js that hasn't been properly included.

On this line merge is called in the standalone file, but it's not defined anywhere inside that file:
https://github.com/IonicaBizau/medium-editor-markdown/blob/master/dist/me-markdown.standalone.js#L7

Here merge is defined in he.js:
https://github.com/mathiasbynens/he/blob/master/src/he.js#L89

**Comment by IonicaBizau** [comment]
Good point!

However, I cannot reproduce it in the demo, using the standalone version too: http://ionicabizau.github.io/medium-editor-markdown/

What do you do just before of error throwing?

**Comment by antonagestam** [comment]
@IonicaBizau The error throws on page load as far as I can tell. That is very strange, could it be because I am using `"use strict";` and you're not?

**Comment by IonicaBizau** [comment]
I cannot reproduce it even using `"use strict";`, but definitely the `merge` function should be added.

**Comment by antonagestam** [comment]
@IonicaBizau Cool, just to be clear, my `"use strict";` statement is in the script that calls `new MeMarkdown();`, don't know if that makes any difference. :)

**Comment by fer-ri** [comment]
This is the line which produce error

![image](https://cloud.githubusercontent.com/assets/1922652/6770467/5b47024c-d0f3-11e4-9b0e-c05dcdfc3b9a.png)

This is from my console

![image](https://cloud.githubusercontent.com/assets/1922652/6770473/6a37a8ec-d0f3-11e4-9915-86283bfae58c.png)

And this is my code

![image](https://cloud.githubusercontent.com/assets/1922652/6770476/7d90985e-d0f3-11e4-9f08-055c4397998d.png)

Thanks

**Comment by IonicaBizau** [comment]
I'm on it! Will make the changes in another branch.

**Comment by fer-ri** [comment]
Wow .. very fast response ... 

Thanks :+1:

**Comment by IonicaBizau** [comment]
Yep! Shouldn't be complicated I guess. :smile:

BTW, are there anything special steps to make this error appear? Also, what browser/OS are you using?

**Comment by fer-ri** [comment]
I use latest chrome + win 7 ..

I think its because options that being passed to `MediumEditor` when initialized like this

``` js
contentEditor   = new MediumEditor('.content-editable', {
            buttons: ['bold', 'anchor', 'header2', 'pre'],
            buttonLabels: 'fontawesome',
});
```

:dancer:

**Comment by antonagestam** [comment]
I used stable Chrome on OSX Yosemite if that helps.

**Comment by IonicaBizau** [comment]
See #3 for the rebuilt scripts. You can get the standalone version using:

``` sh
$ wget https://raw.githubusercontent.com/IonicaBizau/medium-editor-markdown/8d41c8fb4e04f94e15a65dfd11ab827fc5a1c0fe/dist/me-markdown.standalone.min.js
```

(or [clicking here](https://raw.githubusercontent.com/IonicaBizau/medium-editor-markdown/8d41c8fb4e04f94e15a65dfd11ab827fc5a1c0fe/dist/me-markdown.standalone.min.js))

**Comment by fer-ri** [comment]
Got error using minified script above ..

![image](https://cloud.githubusercontent.com/assets/1922652/6770653/344cfb3c-d0f9-11e4-8891-8f61346bdfec.png)

**Comment by IonicaBizau** [comment]
@ghprod Can you please switch on the non-minified version and send me the line number where the error appears?

`decode` is not supposed to be called. Instead, it should be `he.decode`.

**Comment by fer-ri** [comment]
here they are

![image](https://cloud.githubusercontent.com/assets/1922652/6770758/222607e2-d0fd-11e4-889d-f55b30535849.png)

**Comment by IonicaBizau** [comment]
@ghprod Good point! [Check now](https://raw.githubusercontent.com/IonicaBizau/medium-editor-markdown/4a8a6d8955675b817d2662301b67c5d8775dd84f/dist/me-markdown.standalone.js).

**Comment by fer-ri** [comment]
I'm sorry Ionica .. still error

![image](https://cloud.githubusercontent.com/assets/1922652/6777113/10c6ca3c-d179-11e4-9f7f-c315908dd830.png)

![image](https://cloud.githubusercontent.com/assets/1922652/6777125/240e27ca-d179-11e4-962f-8bdb95c85657.png)

**Comment by IonicaBizau** [comment]
Since I can't reproduce this error, it's a little bit difficult to commit these changes. Could you provide a JSFiddle reproducing the error?

Thanks!

**Comment by antonagestam** [comment]
@IonicaBizau I'm sorry, but I've moved away from using markdown in my project.

**Comment by fer-ri** [comment]
@IonicaBizau I'm really sorry too, finally i must use codemirror + marked js .. 

cheers for you :beer:

**Comment by IonicaBizau** [comment]
No problem for me. Getting this issue fixed is weird since I don't have any reproduction page.

However, using the `*.no-deps.*` version should be fine:

``` js
<script src="he.js"></script>
<script src="to-markdown.js"></script>
<script src="medium-editor.js"></script>
<script src="me-markdown.no-deps.js"></script>
```

**Comment by fer-ri** [comment]
Yes, 

thats what i did when last time i try to make it works :+1: 

using no-deps should fine for now ..

Thanks

**Comment by IonicaBizau** [comment]
Could anyone create an online demo to reproduce the error?
I know these functions are not defined, but I don't know if the problem is fixed or not if a demo is missing.
