### ISSUE TITLE
Anonymous AMD/RequireJS support

### ISSUE THREAD

**Issue by assembledadam** [IonicaBizau/medium-editor-markdown#21]
Doesn't appear to work nicely with requireJS.

Normally it could be shimmed, but you have `throw new Error("Medium Editor is not loaded on the page.");` which appears to kill any chance of using it!

It was added to MediumEditor here:
https://github.com/yabwe/medium-editor/pull/318/commits/afbf2b6963403afa79802db209604b3ccc237218

**Comment by IonicaBizau** [comment]
Makes sense. I never did this in the past. Contributions are welcome!

**Comment by guillecro** [comment]
Please add dis T_T

**Comment by IonicaBizau** [comment]
When you `require("medium-editor-markdown")` it supposed that it will resolve with a function, which is the extension itself.

Can we reiterate what is the problem here?

**Comment by abepetrillo** [comment]
Apologies for reviving this, but could you provide an example of how the `require` works in the README? I'm struggling to get this to work via webpack.

**Comment by Techworker** [comment]
I deserve to be hated for this, but this works:

```
const MediumEditor = require('medium-editor');
window.MediumEditor = MediumEditor;
const MeMarkdown = require('medium-editor-markdown/dist/me-markdown.standalone').MeMarkdown;
```

**Comment by IonicaBizau** [comment]
Is this still an issue with the latest versions?
