### ISSUE TITLE
Make whitespace trimming optional

### ISSUE THREAD

**Issue by mpseidel** [IonicaBizau/medium-editor-markdown#25]
Had an issue where leading whitespace in my `<pre></pre>` code blocks where removed. Would suggest to make the trimming an option `removeWhitespace` that is `true` by default but can be overwritten.

**Comment by IonicaBizau** [comment]
@mpseidel Of course! That's a good example. Maybe, it should be `trimRight` by default. Probably I didn't think at the `pre` stuff when I wrote that piece of code. 😁

**Comment by mpseidel** [comment]
Make it `trimRight` by default would solve my problem. Could add an option `whitespace` with otions `trimRight`, `trim` for the current impl and `none` ?

**Comment by IonicaBizau** [comment]
I would say trimRight would be enough. It's just to remove the trailing
spaces (if any), so the markdown output is clean. This should be `true`, by
default, but can be overridden.

**Comment by IonicaBizau** [comment]
I replaced `trim` with `trimRight`. If you find any limitations for this one, let me know. I'm going to close this issue for now.
