### ISSUE TITLE
Allow options for to-markdown to be passed through

### ISSUE THREAD

**Issue by mpseidel** [IonicaBizau/medium-editor-markdown#26]
I needed to specify converters for certain tags so I had to made a small change to just pass `toMarkdownOptions` through as part of the existing options object.

**Comment by IonicaBizau** [comment]
Definitely a 👍

**Comment by IonicaBizau** [comment]
Fixed by @annayafi! Thanks! 🍰 /cc #27

**Comment by mpseidel** [comment]
@annayafi awesome :+1:
