### ISSUE TITLE
How to use / what to expect

### ISSUE THREAD

**Issue by perguth** [IonicaBizau/medium-editor-markdown#47]
I come here as a potential medium user who searches for markdown support (I see the value you add to medium 😄 ). How can I use this project? Can I even include it in the official app / or run it as a separate android app (which would also be fine)?

**Comment by IonicaBizau** [comment]
This is an extension for an *unofficial* Medium editor clone (https://github.com/yabwe/medium-editor).

You can check out the examples for how to use it. :grin: If you have any other questions, feel free to open issues.
