### ISSUE TITLE
Initially load markdown into editor

### ISSUE THREAD

**Issue by rbluethl** [IonicaBizau/medium-editor-markdown#50]
Great extension! 💯 

I was wondering if I can load markdown into the editor initially.
For example if I fetch markdown from my server and want to edit an existing text.

Is that possible? Didn't find anything in the docs.

Thanks

**Comment by zigapk** [comment]
Any updates? @IonicaBizau

**Comment by rbluethl** [comment]
Hey @zigapk,

back then, I got it working by converting the markdown to HTML and setting the editor content like this `editor.setContent("<h1>your html</h1>", 0)`.

Hope that helps.

Ronald

**Comment by zigapk** [comment]
Hi @rbluethl,

thanks for your suggestion. Seems to work great!

Thank you,
Ziga
