### ISSUE TITLE
Different naming of option toTurndownOptions

### ISSUE THREAD

**Issue by xzander** [IonicaBizau/medium-editor-markdown#54]
Hello!

In src/medium-editor-md.js in option `toTurndownOptions` word `down` is used in lower case – `var toTurndownOptions = options.toTurndownOptions = Object(options.toTurndownOptions);`
But in dist files (me-markdown.standalone.js and me-markdown.no-deps.js) it is used in camelcase – `var toTurnDownOptions = options.toTurnDownOptions = Object(options.toTurnDownOptions);`

So when I try to pass options to turndown as it said in documentation, it doesn't work.

**Comment by IonicaBizau** [comment]
Is this still an issue?
