### ISSUE TITLE
Markdown content not updating on change in IE11

### ISSUE THREAD

**Issue by peterchappell** [IonicaBizau/medium-editor-markdown#57]
I noticed while testing in IE11 that the markdown content does not update when you make changes in the content editable area.

You can replicate the issue using the project's demo page in IE11:
http://ionicabizau.github.io/medium-editor-markdown/example/

I have fixed this issue locally by adding a `subscribeToMeEditableInputEvent` option:

```
        if (options.subscribeToMeEditableInputEvent) {
            this.base.subscribe('editableInput', handler);
        } else {
            options.events.forEach(function (c) {
                this.element.addEventListener(c, handler);
            }.bind(this));
        }
```

Very happy to submit a PR for this and follow any suggestions that you have for improvements.

**Comment by peterchappell** [comment]
PR is #58

**Comment by IonicaBizau** [comment]
This is fixed I think.
