### ISSUE TITLE
Support nested lists

### ISSUE THREAD

**Issue by mphasize** [IonicaBizau/medium-editor-markdown#6]
The medium-editor supports nested lists, i.e. using tab/shift-tab to increase or decrease indentation.
- first level
  - second a
  - second b

However, if such a nested list is parsed to markdown with this plugin, the nesting is lost and all the bullet points end up on the first level.
- first level
- second a
- second b

It would be great, if we could get full support for nested lists.

**Comment by IonicaBizau** [comment]
Thanks for reporting this! :+1: 

I forwarded it to medium-editor: https://github.com/yabwe/medium-editor/issues/666

**Comment by mphasize** [comment]
Thanks! I didn't realize that the `medium-editor` DOM was the real culprit here.

**Comment by IonicaBizau** [comment]
I'm thinking if we can solve this by having an HTML normalizer, like @domchristie suggested [here](https://github.com/yabwe/medium-editor/issues/666#issuecomment-150595482). @mphasize Any ideas?

So, basically it would be:
1. Take the HTML
2. Normalize it
3. Markdown it

/cc @domchristie

**Comment by IonicaBizau** [comment]
I'm on this! 🍀

**Comment by naguibihab** [comment]
Is there another solution for this issue that can be done on Medium directly?

**Comment by paullintilhac** [comment]
are there any updates on this?

**Comment by kimgysen** [comment]
Open since 2015? This is ridiculous.

**Comment by kimgysen** [comment]
What is ridiculous is that on Medium website you can't indent bullet list!

**Comment by rberger** [comment]
WTF. There STILL is not nested lists on Medium? And you expect people to use this for technical blogs? I have to do so much work to import from Markdown in general and this is the biggest pain
