### ISSUE TITLE
gh-pages demo has a bug in latest Chrome?

### ISSUE THREAD

**Issue by jywarren** [IonicaBizau/medium-editor-markdown#62]
I see there was a release yesterday so not sure if this is related, but I don't see markdown in the right-side column in the gh-pages demo: 

http://ionicabizau.github.io/medium-editor-markdown/example/

![image](https://user-images.githubusercontent.com/24359/64723037-aaae1480-d49d-11e9-9184-f61bd0fbdd1e.png)

Looks like a great library so thank you! Hope this is helpful!

**Comment by jywarren** [comment]
```
me.js:361 Uncaught TypeError: Cannot set property 'MediumEditor' of undefined
    at me.js:361
    at me.js:363
me-markdown.standalone.js:3 Uncaught Error: Medium Editor is not loaded on the page.
    at me-markdown.standalone.js:3
    at me-markdown.standalone.js:1034
main.js:5 Uncaught ReferenceError: MediumEditor is not defined
    at main.js:5
/favicon.ico:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by smeijer** [comment]
Not only Chrome. The demo is just broken.

**Comment by IonicaBizau** [comment]
FIxed it today.
