### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by connorshea** [IonicaBizau/medium-editor-markdown#7]
This extension doesn't appear to support Firefox, which is a significant problem for the project I'm currently using it for.

Any specific reason why?

**Comment by AnthonySuper** [comment]
Note that the [official demo](http://ionicabizau.github.io/medium-editor-markdown/) doesn't work in Firefox on OSX. I can provide a specific version and other information if needed.

**Comment by connorshea** [comment]
So apparently using `innerText` as the `README.md` file suggests isn't supported by Firefox. However, `innerHTML` is, which fixes the entire problem with a 4-character change. So that's cool, I guess.

**Comment by connorshea** [comment]
See also: [this commit](https://github.com/noidedmedia/Fiction-Dock/commit/fa76c713108fb6605654ffa73b64df1cf8c8ae4e)

**Comment by connorshea** [comment]
And [here's my source](http://www.quirksmode.org/dom/html/) that innerText doesn't work in Firefox.

**Comment by IonicaBizau** [comment]
Yeah, indeed, using `innerText` is not Firefox compatible... Thanks for report! :+1:
