### ISSUE TITLE
Create rule

### ISSUE THREAD

**Issue by ct1735x** [IonicaBizau/medium-editor-markdown#72]
Currently, tables created with medium editor doesnt convert to working markdown tables, its just putting spaces everywhere in the markdown instead of using pipes and dashes

Thats is because there is no rule defined in me-markdown.standalone.min.js to handle tables.

I would like to know how I can create a rule to achieve this WYSIWYG to markdown conversion

I already tried @jerrywham solution from issue #31 but it's definetly not working properly.

**Comment by jerrywham** [comment]
My solution is for me-mardown.standalone.js, not for min version which is minified from me-mardown.standalone.js without my code.

**Comment by ct1735x** [comment]
> My solution is for me-mardown.standalone.js, not for min version which is minified from me-mardown.standalone.js without my code.

The problem is exactly the same with me-markdown.standalone.js
This javascript isn't made to handle medium editor tables
-> in me-markdown.standalone.js, there is no mention of "table", "td" , "tr" or pipes

(je crois que tu parles francais, on pourrait gagner du temps)
